// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appStoreVersionSubmissions: AppStoreVersionSubmissions {
		AppStoreVersionSubmissions(path: path + "/appStoreVersionSubmissions")
	}

	public struct AppStoreVersionSubmissions {
		/// Path: `/v1/appStoreVersionSubmissions`
		public let path: String

		@available(*, deprecated, message: "Deprecated")
		public func post(_ body: Shuttle.AppStoreVersionSubmissionCreateRequest) -> Request<Shuttle.AppStoreVersionSubmissionResponse> {
			Request(method: "POST", url: path, body: body, id: "appStoreVersionSubmissions-create_instance")
		}
	}
}
