// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var subscriptionLocalizations: SubscriptionLocalizations {
		SubscriptionLocalizations(path: path + "/subscriptionLocalizations")
	}

	public struct SubscriptionLocalizations {
		/// Path: `/v1/subscriptionLocalizations`
		public let path: String

		public func post(_ body: Shuttle.SubscriptionLocalizationCreateRequest) -> Request<Shuttle.SubscriptionLocalizationResponse> {
			Request(method: "POST", url: path, body: body, id: "subscriptionLocalizations-create_instance")
		}
	}
}
