// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var subscriptionOfferCodeCustomCodes: SubscriptionOfferCodeCustomCodes {
		SubscriptionOfferCodeCustomCodes(path: path + "/subscriptionOfferCodeCustomCodes")
	}

	public struct SubscriptionOfferCodeCustomCodes {
		/// Path: `/v1/subscriptionOfferCodeCustomCodes`
		public let path: String

		public func post(_ body: Shuttle.SubscriptionOfferCodeCustomCodeCreateRequest) -> Request<Shuttle.SubscriptionOfferCodeCustomCodeResponse> {
			Request(method: "POST", url: path, body: body, id: "subscriptionOfferCodeCustomCodes-create_instance")
		}
	}
}
