// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var subscriptionOfferCodes: SubscriptionOfferCodes {
		SubscriptionOfferCodes(path: path + "/subscriptionOfferCodes")
	}

	public struct SubscriptionOfferCodes {
		/// Path: `/v1/subscriptionOfferCodes`
		public let path: String

		public func post(_ body: Shuttle.SubscriptionOfferCodeCreateRequest) -> Request<Shuttle.SubscriptionOfferCodeResponse> {
			Request(method: "POST", url: path, body: body, id: "subscriptionOfferCodes-create_instance")
		}
	}
}
