// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var buildBetaNotifications: BuildBetaNotifications {
		BuildBetaNotifications(path: path + "/buildBetaNotifications")
	}

	public struct BuildBetaNotifications {
		/// Path: `/v1/buildBetaNotifications`
		public let path: String

		public func post(_ body: Shuttle.BuildBetaNotificationCreateRequest) -> Request<Shuttle.BuildBetaNotificationResponse> {
			Request(method: "POST", url: path, body: body, id: "buildBetaNotifications-create_instance")
		}
	}
}
