// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.AppStoreVersions.WithID.Relationships {
	public var build: Build {
		Build(path: path + "/build")
	}

	public struct Build {
		/// Path: `/v1/appStoreVersions/{id}/relationships/build`
		public let path: String

		public var get: Request<Shuttle.AppStoreVersionBuildLinkageResponse> {
			Request(method: "GET", url: path, id: "appStoreVersions-build-get_to_one_relationship")
		}

		public func patch(_ body: Shuttle.AppStoreVersionBuildLinkageRequest) -> Request<Void> {
			Request(method: "PATCH", url: path, body: body, id: "appStoreVersions-build-update_to_one_relationship")
		}
	}
}
