// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var buildBundles: BuildBundles {
		BuildBundles(path: path + "/buildBundles")
	}

	public struct BuildBundles {
		/// Path: `/v1/buildBundles`
		public let path: String
	}
}
