// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var inAppPurchasePriceSchedules: InAppPurchasePriceSchedules {
		InAppPurchasePriceSchedules(path: path + "/inAppPurchasePriceSchedules")
	}

	public struct InAppPurchasePriceSchedules {
		/// Path: `/v1/inAppPurchasePriceSchedules`
		public let path: String

		public func post(_ body: Shuttle.InAppPurchasePriceScheduleCreateRequest) -> Request<Shuttle.InAppPurchasePriceScheduleResponse> {
			Request(method: "POST", url: path, body: body, id: "inAppPurchasePriceSchedules-create_instance")
		}
	}
}
