// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appStoreVersions: AppStoreVersions {
		AppStoreVersions(path: path + "/appStoreVersions")
	}

	public struct AppStoreVersions {
		/// Path: `/v1/appStoreVersions`
		public let path: String

		public func post(_ body: Shuttle.AppStoreVersionCreateRequest) -> Request<Shuttle.AppStoreVersionResponse> {
			Request(method: "POST", url: path, body: body, id: "appStoreVersions-create_instance")
		}
	}
}
