// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.BetaBuildLocalizations.WithID.Relationships {
	public var build: Build {
		Build(path: path + "/build")
	}

	public struct Build {
		/// Path: `/v1/betaBuildLocalizations/{id}/relationships/build`
		public let path: String
	}
}
