// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var scmGitReferences: ScmGitReferences {
		ScmGitReferences(path: path + "/scmGitReferences")
	}

	public struct ScmGitReferences {
		/// Path: `/v1/scmGitReferences`
		public let path: String
	}
}
