// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appEventVideoClips: AppEventVideoClips {
		AppEventVideoClips(path: path + "/appEventVideoClips")
	}

	public struct AppEventVideoClips {
		/// Path: `/v1/appEventVideoClips`
		public let path: String

		public func post(_ body: Shuttle.AppEventVideoClipCreateRequest) -> Request<Shuttle.AppEventVideoClipResponse> {
			Request(method: "POST", url: path, body: body, id: "appEventVideoClips-create_instance")
		}
	}
}
