// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appStoreVersionReleaseRequests: AppStoreVersionReleaseRequests {
		AppStoreVersionReleaseRequests(path: path + "/appStoreVersionReleaseRequests")
	}

	public struct AppStoreVersionReleaseRequests {
		/// Path: `/v1/appStoreVersionReleaseRequests`
		public let path: String

		public func post(_ body: Shuttle.AppStoreVersionReleaseRequestCreateRequest) -> Request<Shuttle.AppStoreVersionReleaseRequestResponse> {
			Request(method: "POST", url: path, body: body, id: "appStoreVersionReleaseRequests-create_instance")
		}
	}
}
