// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.CiWorkflows.WithID.Relationships {
	public var repository: Repository {
		Repository(path: path + "/repository")
	}

	public struct Repository {
		/// Path: `/v1/ciWorkflows/{id}/relationships/repository`
		public let path: String
	}
}
