// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.AppStoreVersions.WithID.Relationships {
	public var appStoreVersionSubmission: AppStoreVersionSubmission {
		AppStoreVersionSubmission(path: path + "/appStoreVersionSubmission")
	}

	public struct AppStoreVersionSubmission {
		/// Path: `/v1/appStoreVersions/{id}/relationships/appStoreVersionSubmission`
		public let path: String
	}
}
