// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appStoreVersionExperiments: AppStoreVersionExperiments {
		AppStoreVersionExperiments(path: path + "/appStoreVersionExperiments")
	}

	public struct AppStoreVersionExperiments {
		/// Path: `/v1/appStoreVersionExperiments`
		public let path: String

		public func post(_ body: Shuttle.AppStoreVersionExperimentCreateRequest) -> Request<Shuttle.AppStoreVersionExperimentResponse> {
			Request(method: "POST", url: path, body: body, id: "appStoreVersionExperiments-create_instance")
		}
	}
}
