// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.Users.WithID.Relationships {
	public var visibleApps: VisibleApps {
		VisibleApps(path: path + "/visibleApps")
	}

	public struct VisibleApps {
		/// Path: `/v1/users/{id}/relationships/visibleApps`
		public let path: String

		public func get(limit: Int? = nil) -> Request<Shuttle.UserVisibleAppsLinkagesResponse> {
			Request(method: "GET", url: path, query: makeGetQuery(limit), id: "users-visibleApps-get_to_many_relationship")
		}

		private func makeGetQuery(_ limit: Int?) -> [(String, String?)] {
			let encoder = URLQueryEncoder()
			encoder.encode(limit, forKey: "limit")
			return encoder.items
		}

		public func post(_ body: Shuttle.UserVisibleAppsLinkagesRequest) -> Request<Void> {
			Request(method: "POST", url: path, body: body, id: "users-visibleApps-create_to_many_relationship")
		}

		public func patch(_ body: Shuttle.UserVisibleAppsLinkagesRequest) -> Request<Void> {
			Request(method: "PATCH", url: path, body: body, id: "users-visibleApps-replace_to_many_relationship")
		}

		public func delete(_ body: Shuttle.UserVisibleAppsLinkagesRequest) -> Request<Void> {
			Request(method: "DELETE", url: path, body: body, id: "users-visibleApps-delete_to_many_relationship")
		}
	}
}
