// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

@propertyWrapper
public struct AppStoreConnectClient {
    
    public var wrappedValue: APIClient
    
    public init(_ token: AppleJWT) {
        self.wrappedValue = APIClient(token: token)
    }
}

public enum AppStoreConnect {
    
    public static var token: AppleJWT! {
        didSet {
            Self.client = APIClient(token: token)
        }
    }
    
    /// Default API Client to be used for all App Store Connect API requests.
    @AppStoreConnectClient(
        Self.token
    )
    public static var client: APIClient
}

public extension APIClient {
    
    convenience init(
        baseURL: URL?,
        sessionConfiguration: URLSessionConfiguration = .default,
        token: JWTToken
    ) {
        self.init(
            configuration: .init(
                baseURL: baseURL,
                sessionConfiguration: sessionConfiguration,
                delegate: JWTRequestsAuthenticator(token)
            )
        )
    }
    
    convenience init(
        token: AppleJWT
    ) {
        self.init(
            baseURL: URL(string: "https://api.appstoreconnect.apple.com"),
            token: token
        )
        
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(secondsFromGMT: 0)
        formatter.calendar = Calendar(identifier: .iso8601)
        self.configuration.encoder.dateEncodingStrategy = .iso8601
        self.configuration.decoder.dateDecodingStrategy = .custom { (decoder) -> Date in
            let container = try decoder.singleValueContainer()
            let dateStr = try container.decode(String.self)
            
            formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXXX"
            if let date = formatter.date(from: dateStr) {
                return date
            }
            formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssXXXXX"
            if let date = formatter.date(from: dateStr) {
                return date
            }
            formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZZZZZ"
            if let date = formatter.date(from: dateStr) {
                return date
            }
            let context = DecodingError.Context(codingPath: [], debugDescription: "Date Decoding Error - \(dateStr)")
            throw DecodingError.typeMismatch(Date.self, context)
        }
    }
}

public extension Request {
    
    func download(using client: APIClient) async throws -> Get.Response<URL> {
        try await client.download(for: self)
    }
    
    var location: URL {
        get async throws {
            try await download(using: AppStoreConnect.client)
                .location
        }
    }
}

public extension Request where Response: Decodable {
    
    func send(using client: APIClient) async throws -> Get.Response<Response> {
        try await client.send(self)
    }
    
    var response: Get.Response<Response> {
        get async throws {
            try await send(using: AppStoreConnect.client)
        }
    }
    
    var value: Response {
        get async throws {
            try await self.response.value
        }
    }
}

public extension Request where Response == Void {
    
    func send(using client: APIClient) async throws -> Get.Response<Response> {
        try await client.send(self)
    }
    
    var response: Get.Response<Void> {
        get async throws {
            try await send(using: AppStoreConnect.client)
        }
    }
    
    var value: Void {
        get async throws {
            try await self.response.value
        }
    }
}

public extension Request where Response == URL {
    
    var response: Get.Response<URL> {
        get async throws {
            try await download(using: AppStoreConnect.client)
        }
    }
}
