// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var routingAppCoverages: RoutingAppCoverages {
		RoutingAppCoverages(path: path + "/routingAppCoverages")
	}

	public struct RoutingAppCoverages {
		/// Path: `/v1/routingAppCoverages`
		public let path: String

		public func post(_ body: Shuttle.RoutingAppCoverageCreateRequest) -> Request<Shuttle.RoutingAppCoverageResponse> {
			Request(method: "POST", url: path, body: body, id: "routingAppCoverages-create_instance")
		}
	}
}
