// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appStoreVersionExperimentTreatments: AppStoreVersionExperimentTreatments {
		AppStoreVersionExperimentTreatments(path: path + "/appStoreVersionExperimentTreatments")
	}

	public struct AppStoreVersionExperimentTreatments {
		/// Path: `/v1/appStoreVersionExperimentTreatments`
		public let path: String

		public func post(_ body: Shuttle.AppStoreVersionExperimentTreatmentCreateRequest) -> Request<Shuttle.AppStoreVersionExperimentTreatmentResponse> {
			Request(method: "POST", url: path, body: body, id: "appStoreVersionExperimentTreatments-create_instance")
		}
	}
}
