// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.AgeRatingDeclarations {
	public func id(_ id: String) -> WithID {
		WithID(path: "\(path)/\(id)")
	}

	public struct WithID {
		/// Path: `/v1/ageRatingDeclarations/{id}`
		public let path: String

		public func patch(_ body: Shuttle.AgeRatingDeclarationUpdateRequest) -> Request<Shuttle.AgeRatingDeclarationResponse> {
			Request(method: "PATCH", url: path, body: body, id: "ageRatingDeclarations-update_instance")
		}
	}
}
