// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var subscriptionGroups: SubscriptionGroups {
		SubscriptionGroups(path: path + "/subscriptionGroups")
	}

	public struct SubscriptionGroups {
		/// Path: `/v1/subscriptionGroups`
		public let path: String

		public func post(_ body: Shuttle.SubscriptionGroupCreateRequest) -> Request<Shuttle.SubscriptionGroupResponse> {
			Request(method: "POST", url: path, body: body, id: "subscriptionGroups-create_instance")
		}
	}
}
