// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appClipDefaultExperiences: AppClipDefaultExperiences {
		AppClipDefaultExperiences(path: path + "/appClipDefaultExperiences")
	}

	public struct AppClipDefaultExperiences {
		/// Path: `/v1/appClipDefaultExperiences`
		public let path: String

		public func post(_ body: Shuttle.AppClipDefaultExperienceCreateRequest) -> Request<Shuttle.AppClipDefaultExperienceResponse> {
			Request(method: "POST", url: path, body: body, id: "appClipDefaultExperiences-create_instance")
		}
	}
}
