// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var endUserLicenseAgreements: EndUserLicenseAgreements {
		EndUserLicenseAgreements(path: path + "/endUserLicenseAgreements")
	}

	public struct EndUserLicenseAgreements {
		/// Path: `/v1/endUserLicenseAgreements`
		public let path: String

		public func post(_ body: Shuttle.EndUserLicenseAgreementCreateRequest) -> Request<Shuttle.EndUserLicenseAgreementResponse> {
			Request(method: "POST", url: path, body: body, id: "endUserLicenseAgreements-create_instance")
		}
	}
}
