// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect {
	public static var v2: V2 {
		V2(path: "/v2")
	}

	public struct V2 {
		/// Path: `/v2`
		public let path: String
	}
}
