// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.AppInfos.WithID.Relationships {
	public var primaryCategory: PrimaryCategory {
		PrimaryCategory(path: path + "/primaryCategory")
	}

	public struct PrimaryCategory {
		/// Path: `/v1/appInfos/{id}/relationships/primaryCategory`
		public let path: String
	}
}
