// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var subscriptionPrices: SubscriptionPrices {
		SubscriptionPrices(path: path + "/subscriptionPrices")
	}

	public struct SubscriptionPrices {
		/// Path: `/v1/subscriptionPrices`
		public let path: String

		public func post(_ body: Shuttle.SubscriptionPriceCreateRequest) -> Request<Shuttle.SubscriptionPriceResponse> {
			Request(method: "POST", url: path, body: body, id: "subscriptionPrices-create_instance")
		}
	}
}
