// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appClipDefaultExperienceLocalizations: AppClipDefaultExperienceLocalizations {
		AppClipDefaultExperienceLocalizations(path: path + "/appClipDefaultExperienceLocalizations")
	}

	public struct AppClipDefaultExperienceLocalizations {
		/// Path: `/v1/appClipDefaultExperienceLocalizations`
		public let path: String

		public func post(_ body: Shuttle.AppClipDefaultExperienceLocalizationCreateRequest) -> Request<Shuttle.AppClipDefaultExperienceLocalizationResponse> {
			Request(method: "POST", url: path, body: body, id: "appClipDefaultExperienceLocalizations-create_instance")
		}
	}
}
