// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appPreOrders: AppPreOrders {
		AppPreOrders(path: path + "/appPreOrders")
	}

	public struct AppPreOrders {
		/// Path: `/v1/appPreOrders`
		public let path: String

		public func post(_ body: Shuttle.AppPreOrderCreateRequest) -> Request<Shuttle.AppPreOrderResponse> {
			Request(method: "POST", url: path, body: body, id: "appPreOrders-create_instance")
		}
	}
}
