// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var ciWorkflows: CiWorkflows {
		CiWorkflows(path: path + "/ciWorkflows")
	}

	public struct CiWorkflows {
		/// Path: `/v1/ciWorkflows`
		public let path: String

		public func post(_ body: Shuttle.CiWorkflowCreateRequest) -> Request<Shuttle.CiWorkflowResponse> {
			Request(method: "POST", url: path, body: body, id: "ciWorkflows-create_instance")
		}
	}
}
