// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appScreenshots: AppScreenshots {
		AppScreenshots(path: path + "/appScreenshots")
	}

	public struct AppScreenshots {
		/// Path: `/v1/appScreenshots`
		public let path: String

		public func post(_ body: Shuttle.AppScreenshotCreateRequest) -> Request<Shuttle.AppScreenshotResponse> {
			Request(method: "POST", url: path, body: body, id: "appScreenshots-create_instance")
		}
	}
}
