// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var reviewSubmissionItems: ReviewSubmissionItems {
		ReviewSubmissionItems(path: path + "/reviewSubmissionItems")
	}

	public struct ReviewSubmissionItems {
		/// Path: `/v1/reviewSubmissionItems`
		public let path: String

		public func post(_ body: Shuttle.ReviewSubmissionItemCreateRequest) -> Request<Shuttle.ReviewSubmissionItemResponse> {
			Request(method: "POST", url: path, body: body, id: "reviewSubmissionItems-create_instance")
		}
	}
}
