// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect {
	public static var v1: V1 {
		V1(path: "/v1")
	}

	public struct V1 {
		/// Path: `/v1`
		public let path: String
	}
}
