// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appClipHeaderImages: AppClipHeaderImages {
		AppClipHeaderImages(path: path + "/appClipHeaderImages")
	}

	public struct AppClipHeaderImages {
		/// Path: `/v1/appClipHeaderImages`
		public let path: String

		public func post(_ body: Shuttle.AppClipHeaderImageCreateRequest) -> Request<Shuttle.AppClipHeaderImageResponse> {
			Request(method: "POST", url: path, body: body, id: "appClipHeaderImages-create_instance")
		}
	}
}
