// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var betaAppClipInvocations: BetaAppClipInvocations {
		BetaAppClipInvocations(path: path + "/betaAppClipInvocations")
	}

	public struct BetaAppClipInvocations {
		/// Path: `/v1/betaAppClipInvocations`
		public let path: String

		public func post(_ body: Shuttle.BetaAppClipInvocationCreateRequest) -> Request<Shuttle.BetaAppClipInvocationResponse> {
			Request(method: "POST", url: path, body: body, id: "betaAppClipInvocations-create_instance")
		}
	}
}
