// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appPrices: AppPrices {
		AppPrices(path: path + "/appPrices")
	}

	public struct AppPrices {
		/// Path: `/v1/appPrices`
		public let path: String
	}
}
