// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.Apps.WithID {
	public var preOrder: PreOrder {
		PreOrder(path: path + "/preOrder")
	}

	public struct PreOrder {
		/// Path: `/v1/apps/{id}/preOrder`
		public let path: String

		public func get(fieldsAppPreOrders: [FieldsAppPreOrders]? = nil) -> Request<Shuttle.AppPreOrderResponse> {
			Request(method: "GET", url: path, query: makeGetQuery(fieldsAppPreOrders), id: "apps-preOrder-get_to_one_related")
		}

		private func makeGetQuery(_ fieldsAppPreOrders: [FieldsAppPreOrders]?) -> [(String, String?)] {
			let encoder = URLQueryEncoder()
			encoder.encode(fieldsAppPreOrders, forKey: "fields[appPreOrders]", explode: false)
			return encoder.items
		}

		public enum FieldsAppPreOrders: String, Codable, CaseIterable {
			case app
			case appReleaseDate
			case preOrderAvailableDate
		}
	}
}
