// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.Apps.WithID.Relationships {
	public var preReleaseVersions: PreReleaseVersions {
		PreReleaseVersions(path: path + "/preReleaseVersions")
	}

	public struct PreReleaseVersions {
		/// Path: `/v1/apps/{id}/relationships/preReleaseVersions`
		public let path: String
	}
}
