// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appInfoLocalizations: AppInfoLocalizations {
		AppInfoLocalizations(path: path + "/appInfoLocalizations")
	}

	public struct AppInfoLocalizations {
		/// Path: `/v1/appInfoLocalizations`
		public let path: String

		public func post(_ body: Shuttle.AppInfoLocalizationCreateRequest) -> Request<Shuttle.AppInfoLocalizationResponse> {
			Request(method: "POST", url: path, body: body, id: "appInfoLocalizations-create_instance")
		}
	}
}
