// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appCustomProductPageVersions: AppCustomProductPageVersions {
		AppCustomProductPageVersions(path: path + "/appCustomProductPageVersions")
	}

	public struct AppCustomProductPageVersions {
		/// Path: `/v1/appCustomProductPageVersions`
		public let path: String

		public func post(_ body: Shuttle.AppCustomProductPageVersionCreateRequest) -> Request<Shuttle.AppCustomProductPageVersionResponse> {
			Request(method: "POST", url: path, body: body, id: "appCustomProductPageVersions-create_instance")
		}
	}
}
