// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appPreviewSets: AppPreviewSets {
		AppPreviewSets(path: path + "/appPreviewSets")
	}

	public struct AppPreviewSets {
		/// Path: `/v1/appPreviewSets`
		public let path: String

		public func post(_ body: Shuttle.AppPreviewSetCreateRequest) -> Request<Shuttle.AppPreviewSetResponse> {
			Request(method: "POST", url: path, body: body, id: "appPreviewSets-create_instance")
		}
	}
}
