// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appEvents: AppEvents {
		AppEvents(path: path + "/appEvents")
	}

	public struct AppEvents {
		/// Path: `/v1/appEvents`
		public let path: String

		public func post(_ body: Shuttle.AppEventCreateRequest) -> Request<Shuttle.AppEventResponse> {
			Request(method: "POST", url: path, body: body, id: "appEvents-create_instance")
		}
	}
}
