// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var betaTesterInvitations: BetaTesterInvitations {
		BetaTesterInvitations(path: path + "/betaTesterInvitations")
	}

	public struct BetaTesterInvitations {
		/// Path: `/v1/betaTesterInvitations`
		public let path: String

		public func post(_ body: Shuttle.BetaTesterInvitationCreateRequest) -> Request<Shuttle.BetaTesterInvitationResponse> {
			Request(method: "POST", url: path, body: body, id: "betaTesterInvitations-create_instance")
		}
	}
}
