// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var ciBuildActions: CiBuildActions {
		CiBuildActions(path: path + "/ciBuildActions")
	}

	public struct CiBuildActions {
		/// Path: `/v1/ciBuildActions`
		public let path: String
	}
}
