// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.SubscriptionGracePeriods {
	public func id(_ id: String) -> WithID {
		WithID(path: "\(path)/\(id)")
	}

	public struct WithID {
		/// Path: `/v1/subscriptionGracePeriods/{id}`
		public let path: String

		public func get(fieldsSubscriptionGracePeriods: [FieldsSubscriptionGracePeriods]? = nil) -> Request<Shuttle.SubscriptionGracePeriodResponse> {
			Request(method: "GET", url: path, query: makeGetQuery(fieldsSubscriptionGracePeriods), id: "subscriptionGracePeriods-get_instance")
		}

		private func makeGetQuery(_ fieldsSubscriptionGracePeriods: [FieldsSubscriptionGracePeriods]?) -> [(String, String?)] {
			let encoder = URLQueryEncoder()
			encoder.encode(fieldsSubscriptionGracePeriods, forKey: "fields[subscriptionGracePeriods]", explode: false)
			return encoder.items
		}

		public enum FieldsSubscriptionGracePeriods: String, Codable, CaseIterable {
			case app
			case optIn
		}

		public func patch(_ body: Shuttle.SubscriptionGracePeriodUpdateRequest) -> Request<Shuttle.SubscriptionGracePeriodResponse> {
			Request(method: "PATCH", url: path, body: body, id: "subscriptionGracePeriods-update_instance")
		}
	}
}
