// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.BetaGroups.WithID.Relationships {
	public var betaTesters: BetaTesters {
		BetaTesters(path: path + "/betaTesters")
	}

	public struct BetaTesters {
		/// Path: `/v1/betaGroups/{id}/relationships/betaTesters`
		public let path: String

		public func get(limit: Int? = nil) -> Request<Shuttle.BetaGroupBetaTestersLinkagesResponse> {
			Request(method: "GET", url: path, query: makeGetQuery(limit), id: "betaGroups-betaTesters-get_to_many_relationship")
		}

		private func makeGetQuery(_ limit: Int?) -> [(String, String?)] {
			let encoder = URLQueryEncoder()
			encoder.encode(limit, forKey: "limit")
			return encoder.items
		}

		public func post(_ body: Shuttle.BetaGroupBetaTestersLinkagesRequest) -> Request<Void> {
			Request(method: "POST", url: path, body: body, id: "betaGroups-betaTesters-create_to_many_relationship")
		}

		public func delete(_ body: Shuttle.BetaGroupBetaTestersLinkagesRequest) -> Request<Void> {
			Request(method: "DELETE", url: path, body: body, id: "betaGroups-betaTesters-delete_to_many_relationship")
		}
	}
}
