// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appStoreReviewDetails: AppStoreReviewDetails {
		AppStoreReviewDetails(path: path + "/appStoreReviewDetails")
	}

	public struct AppStoreReviewDetails {
		/// Path: `/v1/appStoreReviewDetails`
		public let path: String

		public func post(_ body: Shuttle.AppStoreReviewDetailCreateRequest) -> Request<Shuttle.AppStoreReviewDetailResponse> {
			Request(method: "POST", url: path, body: body, id: "appStoreReviewDetails-create_instance")
		}
	}
}
