// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appStoreVersionExperimentTreatmentLocalizations: AppStoreVersionExperimentTreatmentLocalizations {
		AppStoreVersionExperimentTreatmentLocalizations(path: path + "/appStoreVersionExperimentTreatmentLocalizations")
	}

	public struct AppStoreVersionExperimentTreatmentLocalizations {
		/// Path: `/v1/appStoreVersionExperimentTreatmentLocalizations`
		public let path: String

		public func post(_ body: Shuttle.AppStoreVersionExperimentTreatmentLocalizationCreateRequest) -> Request<Shuttle.AppStoreVersionExperimentTreatmentLocalizationResponse> {
			Request(method: "POST", url: path, body: body, id: "appStoreVersionExperimentTreatmentLocalizations-create_instance")
		}
	}
}
