// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.AppClipDefaultExperienceLocalizations.WithID.Relationships {
	public var appClipHeaderImage: AppClipHeaderImage {
		AppClipHeaderImage(path: path + "/appClipHeaderImage")
	}

	public struct AppClipHeaderImage {
		/// Path: `/v1/appClipDefaultExperienceLocalizations/{id}/relationships/appClipHeaderImage`
		public let path: String
	}
}
