// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.AppCategories.WithID.Relationships {
	public var parent: Parent {
		Parent(path: path + "/parent")
	}

	public struct Parent {
		/// Path: `/v1/appCategories/{id}/relationships/parent`
		public let path: String
	}
}
