// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var subscriptionGroupSubmissions: SubscriptionGroupSubmissions {
		SubscriptionGroupSubmissions(path: path + "/subscriptionGroupSubmissions")
	}

	public struct SubscriptionGroupSubmissions {
		/// Path: `/v1/subscriptionGroupSubmissions`
		public let path: String

		public func post(_ body: Shuttle.SubscriptionGroupSubmissionCreateRequest) -> Request<Shuttle.SubscriptionGroupSubmissionResponse> {
			Request(method: "POST", url: path, body: body, id: "subscriptionGroupSubmissions-create_instance")
		}
	}
}
