// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var subscriptionGroupLocalizations: SubscriptionGroupLocalizations {
		SubscriptionGroupLocalizations(path: path + "/subscriptionGroupLocalizations")
	}

	public struct SubscriptionGroupLocalizations {
		/// Path: `/v1/subscriptionGroupLocalizations`
		public let path: String

		public func post(_ body: Shuttle.SubscriptionGroupLocalizationCreateRequest) -> Request<Shuttle.SubscriptionGroupLocalizationResponse> {
			Request(method: "POST", url: path, body: body, id: "subscriptionGroupLocalizations-create_instance")
		}
	}
}
