// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct BundleIDCapabilityUpdateRequest: Encodable {
	public var data: Data

	public struct Data: Encodable, Identifiable {
        public let type: `Type` = .bundleIDCapabilities
		public var id: String
		public var attributes: Attributes?

		public enum `Type`: String, Encodable, CaseIterable {
			case bundleIDCapabilities = "bundleIdCapabilities"
		}

		public struct Attributes: Encodable {
			public var capabilityType: CapabilityType?
			public var settings: [CapabilitySetting]?

			public init(
                capabilityType: CapabilityType? = nil,
                settings: [CapabilitySetting]? = nil
            ) {
				self.capabilityType = capabilityType
				self.settings = settings
			}
		}

		public init(
            id: BundleIDCapability.ID,
            attributes: Attributes? = nil
        ) {
			self.id = id
			self.attributes = attributes
		}
	}

	public init(data: Data) {
		self.data = data
	}
    
    public init(
        id: BundleIDCapability.ID,
        type: CapabilityType?,
        settings: [CapabilitySetting]?
    ) {
        self.init(
            data: .init(
                id: id,
                attributes: .init(
                    capabilityType: type,
                    settings: settings
                )
            )
        )
    }
}
