// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct BundleIDUpdateRequest: Encodable {
	public var data: Data

	public struct Data: Encodable, Identifiable {
        public let type: `Type` = .bundleIDs
        public var id: BundleID.ID
		public var attributes: Attributes?

		public enum `Type`: String, Encodable, CaseIterable {
			case bundleIDs = "bundleIds"
		}

		public struct Attributes: Encodable {
            public var name: BundleID.Name?

            public init(name: BundleID.Name? = nil) {
				self.name = name
			}
		}

		public init(
            id: BundleID.ID,
            attributes: Attributes? = nil
        ) {
			self.id = id
			self.attributes = attributes
		}
	}

	public init(data: Data) {
		self.data = data
	}
    
    public init(
        id: BundleID.ID,
        name: BundleID.Name
    ) {
        self.init(
            data: .init(
                id: id,
                attributes: .init(
                    name: name
                )
            )
        )
    }
}
