// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CertificateCreateRequest: Encodable {
	public var data: Data

	public struct Data: Encodable {
        public let type: `Type` = .certificates
		public var attributes: Attributes

		public enum `Type`: String, Encodable, CaseIterable {
			case certificates
		}

		public struct Attributes: Encodable {
			public var csrContent: String
			public var certificateType: CertificateType

			public init(csrContent: String, certificateType: CertificateType) {
				self.csrContent = csrContent
				self.certificateType = certificateType
			}
		}

		public init(attributes: Attributes) {
			self.attributes = attributes
		}
	}

	public init(data: Data) {
		self.data = data
	}
    
    public init(
        csrContent: String,
        type: CertificateType
    ) {
        self.init(
            data: .init(
                attributes: .init(
                    csrContent: csrContent,
                    certificateType: type
                )
            )
        )
    }
}
