// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct DeviceUpdateRequest: Encodable {
	public var data: Data

	public struct Data: Encodable, Identifiable {
        public let type: `Type` = .devices
        public var id: Device.ID
		public var attributes: Attributes?

		public enum `Type`: String, Encodable, CaseIterable {
			case devices
		}

		public struct Attributes: Encodable {
            public var name: Device.Name?
            public var status: Device.Status?

			public init(
                name: Device.Name? = nil,
                status: Device.Status? = nil
            ) {
				self.name = name
				self.status = status
			}
		}

        public init(
            id: Device.ID,
            attributes: Attributes? = nil
        ) {
			self.id = id
			self.attributes = attributes
		}
	}

	public init(data: Data) {
		self.data = data
	}
    
    public init(
        id: Device.ID,
        name: Device.Name? = nil,
        status: Device.Status
    ) {
        self.init(
            data: .init(
                id: id,
                attributes: .init(
                    name: name,
                    status: status
                )
            )
        )
    }
}
