// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appClipAdvancedExperiences: AppClipAdvancedExperiences {
		AppClipAdvancedExperiences(path: path + "/appClipAdvancedExperiences")
	}

	public struct AppClipAdvancedExperiences {
		/// Path: `/v1/appClipAdvancedExperiences`
		public let path: String

		public func post(_ body: Shuttle.AppClipAdvancedExperienceCreateRequest) -> Request<Shuttle.AppClipAdvancedExperienceResponse> {
			Request(method: "POST", url: path, body: body, id: "appClipAdvancedExperiences-create_instance")
		}
	}
}
