// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var subscriptionIntroductoryOffers: SubscriptionIntroductoryOffers {
		SubscriptionIntroductoryOffers(path: path + "/subscriptionIntroductoryOffers")
	}

	public struct SubscriptionIntroductoryOffers {
		/// Path: `/v1/subscriptionIntroductoryOffers`
		public let path: String

		public func post(_ body: Shuttle.SubscriptionIntroductoryOfferCreateRequest) -> Request<Shuttle.SubscriptionIntroductoryOfferResponse> {
			Request(method: "POST", url: path, body: body, id: "subscriptionIntroductoryOffers-create_instance")
		}
	}
}
