// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.AppInfos.WithID.Relationships {
	public var ageRatingDeclaration: AgeRatingDeclaration {
		AgeRatingDeclaration(path: path + "/ageRatingDeclaration")
	}

	public struct AgeRatingDeclaration {
		/// Path: `/v1/appInfos/{id}/relationships/ageRatingDeclaration`
		public let path: String
	}
}
