// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appScreenshotSets: AppScreenshotSets {
		AppScreenshotSets(path: path + "/appScreenshotSets")
	}

	public struct AppScreenshotSets {
		/// Path: `/v1/appScreenshotSets`
		public let path: String

		public func post(_ body: Shuttle.AppScreenshotSetCreateRequest) -> Request<Shuttle.AppScreenshotSetResponse> {
			Request(method: "POST", url: path, body: body, id: "appScreenshotSets-create_instance")
		}
	}
}
