// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var customerReviewResponses: CustomerReviewResponses {
		CustomerReviewResponses(path: path + "/customerReviewResponses")
	}

	public struct CustomerReviewResponses {
		/// Path: `/v1/customerReviewResponses`
		public let path: String

		public func post(_ body: Shuttle.CustomerReviewResponseV1CreateRequest) -> Request<Shuttle.CustomerReviewResponseV1Response> {
			Request(method: "POST", url: path, body: body, id: "customerReviewResponses-create_instance")
		}
	}
}
