// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var subscriptionPromotionalOffers: SubscriptionPromotionalOffers {
		SubscriptionPromotionalOffers(path: path + "/subscriptionPromotionalOffers")
	}

	public struct SubscriptionPromotionalOffers {
		/// Path: `/v1/subscriptionPromotionalOffers`
		public let path: String

		public func post(_ body: Shuttle.SubscriptionPromotionalOfferCreateRequest) -> Request<Shuttle.SubscriptionPromotionalOfferResponse> {
			Request(method: "POST", url: path, body: body, id: "subscriptionPromotionalOffers-create_instance")
		}
	}
}
