// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.ScmProviders.WithID.Relationships {
	public var repositories: Repositories {
		Repositories(path: path + "/repositories")
	}

	public struct Repositories {
		/// Path: `/v1/scmProviders/{id}/relationships/repositories`
		public let path: String
	}
}
