// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.Apps.WithID.Relationships {
	public var endUserLicenseAgreement: EndUserLicenseAgreement {
		EndUserLicenseAgreement(path: path + "/endUserLicenseAgreement")
	}

	public struct EndUserLicenseAgreement {
		/// Path: `/v1/apps/{id}/relationships/endUserLicenseAgreement`
		public let path: String
	}
}
