// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appStoreVersionPhasedReleases: AppStoreVersionPhasedReleases {
		AppStoreVersionPhasedReleases(path: path + "/appStoreVersionPhasedReleases")
	}

	public struct AppStoreVersionPhasedReleases {
		/// Path: `/v1/appStoreVersionPhasedReleases`
		public let path: String

		public func post(_ body: Shuttle.AppStoreVersionPhasedReleaseCreateRequest) -> Request<Shuttle.AppStoreVersionPhasedReleaseResponse> {
			Request(method: "POST", url: path, body: body, id: "appStoreVersionPhasedReleases-create_instance")
		}
	}
}
