// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var devices: Devices {
		Devices(path: path + "/devices")
	}

	public struct Devices {
		/// Path: `/v1/devices`
		public let path: String

		public func get(parameters: GetParameters? = nil) -> Request<Shuttle.DevicesResponse> {
			Request(method: "GET", url: path, query: parameters?.asQuery, id: "devices-get_collection")
		}

		public struct GetParameters {
            public var filterName: [Device.Name]?
			public var filterPlatform: [BundleIDPlatform]?
			public var filterStatus: [Device.Status]?
			public var filterUdid: [String]?
            public var filterID: [Device.ID]?
			public var sort: [Sort]?
			public var fieldsDevices: [FieldsDevices]?
			public var limit: Int?

			public enum Sort: String, Codable, CaseIterable {
				case id
				case minusid = "-id"
				case name
				case minusname = "-name"
				case platform
				case minusplatform = "-platform"
				case status
				case minusstatus = "-status"
				case udid
				case minusudid = "-udid"
			}

			public enum FieldsDevices: String, Codable, CaseIterable {
				case addedDate
				case deviceClass
				case model
				case name
				case platform
				case status
				case udid
			}

			public init(
                filterName: [Device.Name]? = nil,
                filterPlatform: [BundleIDPlatform]? = nil,
                filterStatus: [Device.Status]? = nil,
                filterUdid: [String]? = nil,
                filterID: [Device.ID]? = nil,
                sort: [Sort]? = nil,
                fieldsDevices: [FieldsDevices]? = nil,
                limit: Int? = nil
            ) {
				self.filterName = filterName
				self.filterPlatform = filterPlatform
				self.filterStatus = filterStatus
				self.filterUdid = filterUdid
				self.filterID = filterID
				self.sort = sort
				self.fieldsDevices = fieldsDevices
				self.limit = limit
			}

			public var asQuery: [(String, String?)] {
				let encoder = URLQueryEncoder(explode: false)
				encoder.encode(filterName, forKey: "filter[name]")
				encoder.encode(filterPlatform, forKey: "filter[platform]")
				encoder.encode(filterStatus, forKey: "filter[status]")
				encoder.encode(filterUdid, forKey: "filter[udid]")
				encoder.encode(filterID, forKey: "filter[id]")
				encoder.encode(sort, forKey: "sort")
				encoder.encode(fieldsDevices, forKey: "fields[devices]")
				encoder.encode(limit, forKey: "limit")
				return encoder.items
			}
		}

		public func post(_ body: Shuttle.DeviceCreateRequest) -> Request<Shuttle.DeviceResponse> {
			Request(method: "POST", url: path, body: body, id: "devices-create_instance")
		}
	}
}
