// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.Apps.WithID.Relationships {
	public var appCustomProductPages: AppCustomProductPages {
		AppCustomProductPages(path: path + "/appCustomProductPages")
	}

	public struct AppCustomProductPages {
		/// Path: `/v1/apps/{id}/relationships/appCustomProductPages`
		public let path: String
	}
}
