// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.SubscriptionOfferCodeOneTimeUseCodes.WithID {
	public var values: Values {
		Values(path: path + "/values")
	}

	public struct Values {
		/// Path: `/v1/subscriptionOfferCodeOneTimeUseCodes/{id}/values`
		public let path: String

		public var get: Request<String> {
			Request(method: "GET", url: path, id: "subscriptionOfferCodeOneTimeUseCodes-values-get_to_one_related")
		}
	}
}
