// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.BetaGroups.WithID.Relationships {
	public var builds: Builds {
		Builds(path: path + "/builds")
	}

	public struct Builds {
		/// Path: `/v1/betaGroups/{id}/relationships/builds`
		public let path: String

		public func get(limit: Int? = nil) -> Request<Shuttle.BetaGroupBuildsLinkagesResponse> {
			Request(method: "GET", url: path, query: makeGetQuery(limit), id: "betaGroups-builds-get_to_many_relationship")
		}

		private func makeGetQuery(_ limit: Int?) -> [(String, String?)] {
			let encoder = URLQueryEncoder()
			encoder.encode(limit, forKey: "limit")
			return encoder.items
		}

		public func post(_ body: Shuttle.BetaGroupBuildsLinkagesRequest) -> Request<Void> {
			Request(method: "POST", url: path, body: body, id: "betaGroups-builds-create_to_many_relationship")
		}

		public func delete(_ body: Shuttle.BetaGroupBuildsLinkagesRequest) -> Request<Void> {
			Request(method: "DELETE", url: path, body: body, id: "betaGroups-builds-delete_to_many_relationship")
		}
	}
}
