// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.Apps.WithID.Relationships {
	public var betaAppReviewDetail: BetaAppReviewDetail {
		BetaAppReviewDetail(path: path + "/betaAppReviewDetail")
	}

	public struct BetaAppReviewDetail {
		/// Path: `/v1/apps/{id}/relationships/betaAppReviewDetail`
		public let path: String
	}
}
