// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var promotedPurchases: PromotedPurchases {
		PromotedPurchases(path: path + "/promotedPurchases")
	}

	public struct PromotedPurchases {
		/// Path: `/v1/promotedPurchases`
		public let path: String

		public func post(_ body: Shuttle.PromotedPurchaseCreateRequest) -> Request<Shuttle.PromotedPurchaseResponse> {
			Request(method: "POST", url: path, body: body, id: "promotedPurchases-create_instance")
		}
	}
}
