// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var ageRatingDeclarations: AgeRatingDeclarations {
		AgeRatingDeclarations(path: path + "/ageRatingDeclarations")
	}

	public struct AgeRatingDeclarations {
		/// Path: `/v1/ageRatingDeclarations`
		public let path: String
	}
}
