// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.BetaAppClipInvocationLocalizations {
	public func id(_ id: String) -> WithID {
		WithID(path: "\(path)/\(id)")
	}

	public struct WithID {
		/// Path: `/v1/betaAppClipInvocationLocalizations/{id}`
		public let path: String

		public func patch(_ body: Shuttle.BetaAppClipInvocationLocalizationUpdateRequest) -> Request<Shuttle.BetaAppClipInvocationLocalizationResponse> {
			Request(method: "PATCH", url: path, body: body, id: "betaAppClipInvocationLocalizations-update_instance")
		}

		public var delete: Request<Void> {
			Request(method: "DELETE", url: path, id: "betaAppClipInvocationLocalizations-delete_instance")
		}
	}
}
