// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appEventScreenshots: AppEventScreenshots {
		AppEventScreenshots(path: path + "/appEventScreenshots")
	}

	public struct AppEventScreenshots {
		/// Path: `/v1/appEventScreenshots`
		public let path: String

		public func post(_ body: Shuttle.AppEventScreenshotCreateRequest) -> Request<Shuttle.AppEventScreenshotResponse> {
			Request(method: "POST", url: path, body: body, id: "appEventScreenshots-create_instance")
		}
	}
}
