// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V2.InAppPurchases.WithID.Relationships {
	public var inAppPurchaseLocalizations: InAppPurchaseLocalizations {
		InAppPurchaseLocalizations(path: path + "/inAppPurchaseLocalizations")
	}

	public struct InAppPurchaseLocalizations {
		/// Path: `/v2/inAppPurchases/{id}/relationships/inAppPurchaseLocalizations`
		public let path: String
	}
}
