// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.AppInfos.WithID.Relationships {
	public var secondarySubcategoryTwo: SecondarySubcategoryTwo {
		SecondarySubcategoryTwo(path: path + "/secondarySubcategoryTwo")
	}

	public struct SecondarySubcategoryTwo {
		/// Path: `/v1/appInfos/{id}/relationships/secondarySubcategoryTwo`
		public let path: String
	}
}
