// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.CiXcodeVersions.WithID.Relationships {
	public var macOsVersions: MacOsVersions {
		MacOsVersions(path: path + "/macOsVersions")
	}

	public struct MacOsVersions {
		/// Path: `/v1/ciXcodeVersions/{id}/relationships/macOsVersions`
		public let path: String
	}
}
