// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var inAppPurchaseLocalizations: InAppPurchaseLocalizations {
		InAppPurchaseLocalizations(path: path + "/inAppPurchaseLocalizations")
	}

	public struct InAppPurchaseLocalizations {
		/// Path: `/v1/inAppPurchaseLocalizations`
		public let path: String

		public func post(_ body: Shuttle.InAppPurchaseLocalizationCreateRequest) -> Request<Shuttle.InAppPurchaseLocalizationResponse> {
			Request(method: "POST", url: path, body: body, id: "inAppPurchaseLocalizations-create_instance")
		}
	}
}
