// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.Builds.WithID.Relationships {
	public var diagnosticSignatures: DiagnosticSignatures {
		DiagnosticSignatures(path: path + "/diagnosticSignatures")
	}

	public struct DiagnosticSignatures {
		/// Path: `/v1/builds/{id}/relationships/diagnosticSignatures`
		public let path: String
	}
}
