// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var appPreviews: AppPreviews {
		AppPreviews(path: path + "/appPreviews")
	}

	public struct AppPreviews {
		/// Path: `/v1/appPreviews`
		public let path: String

		public func post(_ body: Shuttle.AppPreviewCreateRequest) -> Request<Shuttle.AppPreviewResponse> {
			Request(method: "POST", url: path, body: body, id: "appPreviews-create_instance")
		}
	}
}
