// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1.AppInfos.WithID.Relationships {
	public var secondarySubcategoryOne: SecondarySubcategoryOne {
		SecondarySubcategoryOne(path: path + "/secondarySubcategoryOne")
	}

	public struct SecondarySubcategoryOne {
		/// Path: `/v1/appInfos/{id}/relationships/secondarySubcategoryOne`
		public let path: String
	}
}
