// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var subscriptionOfferCodeOneTimeUseCodes: SubscriptionOfferCodeOneTimeUseCodes {
		SubscriptionOfferCodeOneTimeUseCodes(path: path + "/subscriptionOfferCodeOneTimeUseCodes")
	}

	public struct SubscriptionOfferCodeOneTimeUseCodes {
		/// Path: `/v1/subscriptionOfferCodeOneTimeUseCodes`
		public let path: String

		public func post(_ body: Shuttle.SubscriptionOfferCodeOneTimeUseCodeCreateRequest) -> Request<Shuttle.SubscriptionOfferCodeOneTimeUseCodeResponse> {
			Request(method: "POST", url: path, body: body, id: "subscriptionOfferCodeOneTimeUseCodes-create_instance")
		}
	}
}
