// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var gameCenterEnabledVersions: GameCenterEnabledVersions {
		GameCenterEnabledVersions(path: path + "/gameCenterEnabledVersions")
	}

	public struct GameCenterEnabledVersions {
		/// Path: `/v1/gameCenterEnabledVersions`
		public let path: String
	}
}
