// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension AppStoreConnect.V1 {
	public var inAppPurchaseSubmissions: InAppPurchaseSubmissions {
		InAppPurchaseSubmissions(path: path + "/inAppPurchaseSubmissions")
	}

	public struct InAppPurchaseSubmissions {
		/// Path: `/v1/inAppPurchaseSubmissions`
		public let path: String

		public func post(_ body: Shuttle.InAppPurchaseSubmissionCreateRequest) -> Request<Shuttle.InAppPurchaseSubmissionResponse> {
			Request(method: "POST", url: path, body: body, id: "inAppPurchaseSubmissions-create_instance")
		}
	}
}
