// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct BundleIDCreateRequest: Encodable {
	public var data: Data

	public struct Data: Encodable {
        public let type: `Type` = .bundleIDs
		public var attributes: Attributes

		public enum `Type`: String, Encodable, CaseIterable {
			case bundleIDs = "bundleIds"
		}

		public struct Attributes: Encodable {
            public var name: BundleID.Name
			public var platform: BundleIDPlatform
            public var identifier: BundleID.Identifier
			public var seedID: String?

			public init(
                name: BundleID.Name,
                platform: BundleIDPlatform,
                identifier: BundleID.Identifier,
                seedID: String? = nil
            ) {
				self.name = name
				self.platform = platform
				self.identifier = identifier
				self.seedID = seedID
			}

			private enum CodingKeys: String, CodingKey {
				case name
				case platform
				case identifier
				case seedID = "seedId"
			}
		}

		public init(attributes: Attributes) {
			self.attributes = attributes
		}
	}

	public init(data: Data) {
		self.data = data
	}
    
    public init(
        name: BundleID.Name,
        platform: BundleIDPlatform,
        identifier: BundleID.Identifier,
        seedID: String? = nil
    ) {
        self.init(
            data: .init(
                attributes: .init(
                    name: name,
                    platform: platform,
                    identifier: identifier,
                    seedID: seedID
                )
            )
        )
    }
}
