// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct DeviceCreateRequest: Encodable {
	public var data: Data

	public struct Data: Encodable {
        public let type: `Type` = .devices
		public var attributes: Attributes

		public enum `Type`: String, Codable, CaseIterable {
			case devices
		}

		public struct Attributes: Encodable {
			public var name: String
			public var platform: BundleIDPlatform
			public var udid: String

			public init(
                name: Device.Name,
                platform: BundleIDPlatform,
                udid: Device.Identifier
            ) {
				self.name = name
				self.platform = platform
				self.udid = udid
			}
		}

        public init(attributes: Attributes) {
			self.attributes = attributes
		}
	}

	public init(data: Data) {
		self.data = data
	}
    
    public init(
        name: Device.Name,
        udid: Device.Identifier,
        platform: BundleIDPlatform
    ) {
        self.init(
            data: .init(
                attributes: .init(
                    name: name,
                    platform: platform,
                    udid: udid
                )
            )
        )
    }
}
