// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder
import Shuttle

extension AppStoreConnect.V1.Profiles.WithID {
	public var devices: Devices {
		Devices(path: path + "/devices")
	}

	public struct Devices {
		/// Path: `/v1/profiles/{id}/devices`
		public let path: String

		public func get(
            deviceFields: [Device.Attributes.Field]? = nil,
            limit: Int? = nil
        ) -> Request<DevicesResponse> {
			Request(
                method: "GET",
                url: path,
                query: makeGetQuery(deviceFields, limit),
                id: "profiles-devices-get_to_many_related"
            )
		}

		private func makeGetQuery(
            _ deviceFields: [Device.Attributes.Field]?,
            _ limit: Int?
        ) -> [(String, String?)] {
			let encoder = URLQueryEncoder()
			encoder.encode(deviceFields, forKey: "fields[devices]", explode: false)
			encoder.encode(limit, forKey: "limit")
			return encoder.items
		}
	}
}
