// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder
import Shuttle

extension AppStoreConnect.V1.Devices {
	public func id(_ id: String) -> WithID {
		WithID(path: "\(path)/\(id)")
	}

	public struct WithID {
		/// Path: `/v1/devices/{id}`
		public let path: String

		public func get(
            deviceFields: [Device.Attributes.Field]? = nil
        ) -> Request<DeviceResponse> {
			Request(
                method: "GET",
                url: path,
                query: makeGetQuery(deviceFields),
                id: "devices-get_instance"
            )
		}

		private func makeGetQuery(
            _ deviceFields: [Device.Attributes.Field]?
        ) -> [(String, String?)] {
			let encoder = URLQueryEncoder()
			encoder.encode(deviceFields, forKey: "fields[devices]", explode: false)
			return encoder.items
		}

		public func patch(_ body: DeviceUpdateRequest) -> Request<DeviceResponse> {
			Request(
                method: "PATCH",
                url: path,
                body: body,
                id: "devices-update_instance"
            )
		}
	}
}
