// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder
import Shuttle

extension AppStoreConnect.V1.BundleIDs.WithID {
	public var profiles: Profiles {
		Profiles(path: path + "/profiles")
	}

	public struct Profiles {
		/// Path: `/v1/bundleIds/{id}/profiles`
		public let path: String

		public func get(
            profileFields: [Profile.Attributes.Field]? = nil,
            limit: Int? = nil
        ) -> Request<ProfilesResponse> {
			Request(
                method: "GET",
                url: path,
                query: makeGetQuery(profileFields, limit),
                id: "bundleIds-profiles-get_to_many_related"
            )
		}

		private func makeGetQuery(
            _ profileFields: [Profile.Attributes.Field]?,
            _ limit: Int? = .maxResources
        ) -> [(String, String?)] {
			let encoder = URLQueryEncoder()
			encoder.encode(profileFields, forKey: "fields[profiles]", explode: false)
			encoder.encode(limit, forKey: "limit")
			return encoder.items
		}
	}
}
