// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder
import Shuttle

extension AppStoreConnect.V1.Profiles.WithID {
    public var certificates: Self.Certificates {
		Certificates(path: path + "/certificates")
	}

	public struct Certificates {
		/// Path: `/v1/profiles/{id}/certificates`
		public let path: String

		public func get(
            certificateFields: [Certificate.Attributes.Field]? = nil,
            limit: Int? = .maxResources
        ) -> Request<CertificatesResponse> {
			Request(
                method: "GET",
                url: path,
                query: makeGetQuery(certificateFields, limit),
                id: "profiles-certificates-get_to_many_related"
            )
		}

		private func makeGetQuery(
            _ certificateFields: [Certificate.Attributes.Field]?,
            _ limit: Int?
        ) -> [(String, String?)] {
			let encoder = URLQueryEncoder()
			encoder.encode(certificateFields, forKey: "fields[certificates]", explode: false)
			encoder.encode(limit, forKey: "limit")
			return encoder.items
		}
	}
}
