// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PagedDocumentLinks: Codable {
	public let this: URL
	public let first: URL?
	public let next: URL?

	public init(
        this: URL,
        first: URL? = nil,
        next: URL? = nil
    ) {
		self.this = this
		self.first = first
		self.next = next
	}

	private enum CodingKeys: String, CodingKey {
		case this = "self"
		case first
		case next
	}
}
